### ISSUE TITLE
Incorrect Last seen 

### ISSUE THREAD

**Issue by tgalal** [tgalal/wazapp#103]
As reported:
"last seen" changes to the current time whenever you send a message and then changes back sometimes.

see http://talk.maemo.org/showpost.php?p=1268873&postcount=4920
and http://talk.maemo.org/showpost.php?p=1268929&postcount=4957

**Comment by CepiPerez** [comment]
I think I've fixed it, now "last seen" is blank when you open a conversation until it's updated
Can you confirm?

**Comment by tgalal** [comment]
Can you create a pull request ? :P

**Comment by CepiPerez** [comment]
It's already in dev branch (and RC too)
Everytime you open a conv, the status is hidden, until last seen is loaded
Isn't it working?

**Comment by CepiPerez** [comment]
Line 22 in Conversation.qml says:
ustatus.state = "default"

**Comment by tgalal** [comment]
What you say is true. But problem is after it is loaded, if you send a message, it changes to current time. Correct behavior is that it shouldn't change. I found problem source is onPaused signal is fired inside messagesReady in main.qml. And onPaused sets lastSeen to now. I'm taking care of it
