### ISSUE TITLE
Initial Groupsync missing

### ISSUE THREAD

**Issue by MoritzJT** [tgalal/wazapp#142]
Current behaviour

Starting off a fresh database:

No groups are synced

After receiving a message from a group, the group is added to the database but it's not automatically pulling groupdetails like image and so on, sometimes does but not regularly

Correct behaviour:

Wazapp starts off a new database / hidden / deleted group

All groups sync without receiving a message first so they can be administered or left without any initial messaging necessary.

**Comment by tgalal** [comment]
duplicate of #126
