### ISSUE TITLE
Message sound not working while listening to music

### ISSUE THREAD

**Issue by huuhtaneno** [tgalal/wazapp#153]
When I listen to music through my earphones and receive a message there is no sound but more like of a crackle or pop.

**Comment by huuhtaneno** [comment]
This seems to have been fixed in the latest Nightly.

**Comment by CODeRUS** [comment]
do not close issues while not wixed in master build at wazapp.im =)
and yes, system notifications will solve that problem.

**Comment by huuhtaneno** [comment]
Ah sorry! Won't happen again :)
