### ISSUE TITLE
Message-tone is always set to max sound level.

### ISSUE THREAD

**Issue by Alfdererste** [tgalal/wazapp#166]
can't set different sound levels. It is always set to maximum.
Except setting to mute.

**Comment by CODeRUS** [comment]
message sound level follows profile volume (blue) not media volume (pink) level bar. check it.

**Comment by Alfdererste** [comment]
Yes, i used the blue level bar.
The profile "mute" and "beep" are working.
On "ringring" every 4 levels are as loud as Max level(compared to normal sms-tone).
I have Pr1.3 installed and wazapp 0.9.12. Same with devel-versions 0.8.11.8 and 0.8.11.11.
I had no Problems with early 0.2.6 version.

**Comment by Alfdererste** [comment]
The new Wazapp Version 0.9.13 fix it for me!
Sound levels are now working correct.

Thank You :)
