### ISSUE TITLE
Squircle notification.

### ISSUE THREAD

**Issue by dcastrog** [tgalal/wazapp#18]
There should be a squircle in notification widgets instead of plain square profile picture.

**Comment by CepiPerez** [comment]
I don't know if its possible, since it uses the mnotification library
I'm thinking about create rounded images for all wazapp contacts and use them in notifications
@tgalal: what do you think?

**Comment by tgalal** [comment]
I don't think it's even necessary at the moment at all. We got more important things for now ;) So we could just leave this issue open for now.

**Comment by CepiPerez** [comment]
You're right, but it was easy to do and I did it.
But I'm wondering what icon will be showed when a group message is received.

**Comment by tgalal** [comment]
Groups in whatsapp can have icons (set by group members), so either that or a default icon. But don't worry about group icons I'll take care of it.

**Comment by knobtviker** [comment]
Can't the image for notifications be manipulated in Python with a mask and then pushed to mnotification?

**Comment by CepiPerez** [comment]
I've already made this, but not that way
Now wazapp make squircle icons for all contacts at startup
And use those icons in all the interface

2012/6/3 knobtviker
reply@reply.github.com:

**Comment by knobtviker** [comment]
So basically you cached the contacts image avatars? OK.

**Comment by CepiPerez** [comment]
Yes
But I'm thinking about change it and make the icons before the
notification is launched to improve startup

2012/6/3 knobtviker
reply@reply.github.com:
