### ISSUE TITLE
Internaltionals number don't get add to my contacts

### ISSUE THREAD

**Issue by e0x** [tgalal/wazapp#222]
hello , i am from dominican republic using wazapp lasted corderus build 
wazapp_0.9.13~nightly_22112012_armel.deb

all my local contacts get sync just fine ( dominican republic numbers ) but  i have 2 contacts one from panama and another for argentina when i do the sync i don't get it add to my wazapp contacts list, only when they message me i can add it to my contacts list.

if you need another info please tell me i will happy to test anything to get this solved

Thanks

**Comment by CODeRUS** [comment]
you cant report bugs using nightly versions. only master builds from wazapp.im

**Comment by e0x** [comment]
meh
