### ISSUE TITLE
Logon Failed error

### ISSUE THREAD

**Issue by soryuuha** [tgalal/wazapp#241]
As title, logon failed error came again..reverify account didnt help

**Comment by CODeRUS** [comment]
as google whatsapp have login troubles in new year days.
just launch wazapp and it will connect in some minutes.

**Comment by abustany** [comment]
It also seems that the verification code format changed: the SMS I received had something of the form 000-000. Re-verification only worked after I entered the 6 digits and the - (via copy paste since the keyboard only shows numbers), but login still fails.

**Comment by wao5257** [comment]
same here..I deleted my account, created a new one and verified it, but still no change :(

**Comment by soryuuha** [comment]
@coderus did you mean that, after it shows "Logon Failed! (Edit Account)"
message, Wazapp will reconnect back after few minutes?
Must be me, I can't get it to connect even after two hours.

**Comment by CODeRUS** [comment]
I just had some connection troubles, but it solved itself. Check last pages on TMO.

**Comment by CODeRUS** [comment]
okay, relaunched wazapp and i'm with you now :D

**Comment by abustany** [comment]
@CODeRUS Do you also get the "new format" for the registration code? ie. XXX-XXX instead of XXX digits. Just wondering if there are places in the wazapp code that assume that the verification code is three digits (and how that interacts with the actual login).

**Comment by soryuuha** [comment]
6 digits login already working with >v0.9.15. just key in the number
without "-".
but this, now, is latter issue.

**Comment by soryuuha** [comment]
fixed

**Comment by stavon** [comment]
wazzapp is sayin line blocked..after it hd said login failed! i had deleted the account nd i was tryin tu re verify

**Comment by CODeRUS** [comment]
http://www.whatsapp.com/faq/general/23154266
