### ISSUE TITLE
Bubble chat with image missing on next wazapp launch 

### ISSUE THREAD

**Issue by soryuuha** [tgalal/wazapp#243]
Whn  stuck at retrieving image(indefinite initializing), quit and relaunch wazapp to redownload back the image. 

the specific image bubble will went missing for good.

any work around for this?

**Comment by CODeRUS** [comment]
why not to show log?

**Comment by soryuuha** [comment]
will update with logs later.

**Comment by soryuuha** [comment]
logs : http://talk.maemo.org/showpost.php?p=1310833&postcount=8776
i believe this fixed my issue : http://talk.maemo.org/showpost.php?p=1310858&postcount=8779 eventhough the picture bubble remain broken and chat logs albeit disarranged :)

**Comment by soryuuha** [comment]
PMed @CODeRUS at TMO for my *.db file
