### ISSUE TITLE
Porting to desktop application?

### ISSUE THREAD

**Issue by dswd** [tgalal/wazapp#251]
Hi,

I just discovered that this app is mostly written in python and QT. Would this app be a good starting point for a whatsapp desktop application or is it too phone specific?
How much of the code base could be reused in such a desktop application?

To clearify: I do not ask you to port it to the desktop, I just ask if the code base would be a good starting point and how much effort it would take for an experienced python programmer.

Depending on your answer I would like to try my luck but I certainly would not object if other developers want to join in.

**Comment by tgalal** [comment]
Just needs a UI
