### ISSUE TITLE
Block Number Problem! New Update. Block number if send 17 msg!

### ISSUE THREAD

**Issue by lahmacuns** [tgalal/wazapp#254]
Whatsapp has a new precaution. It block after 17 messages. My trials:
Reconnection for each message and with 2 seconds delay, my number is blocked after 17 messages. Changed the message content randomly and the result was the same. Changed IP and same results.

They have a new precaution. Anybody have a solution? I am planning to use it for newslettering this weekend.

PS: It's not spam or marketing. I have a 2500 member institution.

**Comment by CODeRUS** [comment]
wazapp bug? really? how you sending 17 messages with 2 seconds reconnect using wazapp? explain.

**Comment by tgalal** [comment]
lol
