### ISSUE TITLE
Problem with sending media

### ISSUE THREAD

**Issue by thedead1440** [tgalal/wazapp#259]
Since the past ~12hours, posters on the TMO thread are reporting that while they are able to receive media from contacts, they are unable to send any media.

Hope you could look into it and/or post an update on the thread :)

Thanks!

27/03: Due to some people especially Taha93 not understanding the difference between github and a forum its better to keep this issue closed instead of allowing spam to busy devs.

**Comment by Taha93** [comment]
Yep Please Fix It :(

**Comment by tgalal** [comment]
Working on it

**Comment by Taha93** [comment]
Thank you :)

**Comment by timod-98** [comment]
When you have fixed it (that'd be great!), could you please share which .pys you have edited? Then I can resume using Coderus build. Thanks! :)

**Comment by ahmadyosry** [comment]
i cant send any media to anyone
but i can recieve
so can anyone help tell me what shoulfd i do ?

**Comment by Taha93** [comment]
Tgalal is working on it so you need to be patient buddy :)

**Comment by Taha93** [comment]
How long its going to take to fix the issue @tgalal

**Comment by susha987** [comment]
i've got the same problem :(

**Comment by CODeRUS** [comment]
@Taha93 be patient yourself.

**Comment by Alkabten77** [comment]
Gent,
still the propleame same or in my N9 only, there is any update

BR
Alkabten
