### ISSUE TITLE
Frequent crashing

### ISSUE THREAD

**Issue by aboodesta** [tgalal/wazapp#26]
The applications shows the " wazapp stop responding, close now? " Message way too frequently on 0.24 and even on the first boot of 0.25. This especially happens when changing orientation, but not always as its sometimes random. Sometimes the application almost immediately goes back to being operational and the message box disappears and this happens most of the time, but a few times it stayed stuck until I closed it by swiping down.

**Comment by aboodesta** [comment]
I meant even on version 0.26's first boot up

**Comment by dcastrog** [comment]
This happens to me frequently when synching contatcs
