### ISSUE TITLE
Not able to send any message (not only media)

### ISSUE THREAD

**Issue by elvisenna** [tgalal/wazapp#260]
Hi guys. I've been having this issue for some time now. I can receive messages and everything, but I just can't send any text (not only media, but anything). I can write the message, when I click on SEND, the message just disappears and won't appear on the dialogue box. I tried reinstalling Wazapp, reboot and nothing seems to fix the problem. Anyone know this?

**Comment by yazmin1234** [comment]
hopefully soon fix this little problem of being able to send pictures..TGALAL...
