### ISSUE TITLE
Attachment Issue

### ISSUE THREAD

**Issue by Alan71** [tgalal/wazapp#261]
Hi Tgala, 
Thanks the Improvement on Wazoo for N9....before I Was Able to send Pic. from N9..now I am uable to do it....it just says  initialising..

Hopeimg for this  issue to be solved, it's a Nice app.

**Comment by Ipuna** [comment]
Have the same issue. Reinstall did not help. Hope get a fix soon!

**Comment by hernancastillo** [comment]
Same here... I noticed that a few days back. Hope you can work on it soon.

**Comment by Alan71** [comment]
Dear tgalal

awating your Reply/update on the attachment issue...

**Comment by Alan71** [comment]
Dear Tgalal,

Pls. Advise about The attachment issue

**Comment by CODeRUS** [comment]
please don't be idiot and read before asking :)

**Comment by CODeRUS** [comment]
for dummies: https://github.com/tgalal/wazapp/issues/259#issuecomment-15362269
