### ISSUE TITLE
Integrate Contacts

### ISSUE THREAD

**Issue by momoelz** [tgalal/wazapp#264]
In n9 would be nice to integrate Contacts with Phone Contacts to have just like skype an Option to send message to contact,
It would  be also awsome to integrate the whole whatsapp into the system just like Chat :) (Facebook, skype etc) and have an status bar option to be available or not :)

The media shared with a contact i must click back from the picture and go on the next to view the next picture it should be possibel to switch by swiping the pictures

**Comment by CODeRUS** [comment]
it will be not Wazapp then :D

**Comment by momoelz** [comment]
why not :D

**Comment by phako** [comment]
Because most of the stuff you would like to have it integrated to is closed and not extensible.

**Comment by momoelz** [comment]
what about the share feature so that u can share from gallery or so?

**Comment by Thaodan** [comment]
One way would be to port wazapp to a telepathy tube, this would help to port wazapp to desktop too.
