### ISSUE TITLE
failed registration v0.9.20

### ISSUE THREAD

**Issue by ninaness** [tgalal/wazapp#274]
![2013-05-10_08-07-21](https://f.cloud.github.com/assets/4391752/488510/65a131d6-b980-11e2-994f-ce0fbf7333b8.png)
![2013-05-10_08-08-36](https://f.cloud.github.com/assets/4391752/488519/c2a55790-b980-11e2-893d-305c765efe12.png)

Hi Tarek.

I just downloaded the newest version (as i am aware of) from the openwhatsapp page. I used Wazzap beta versions before and it works really well in my N9 Meego PR1.2 and 1.3. However, my phone battery died and I had it repaired. I just got it back but the newest version 0.9.20 always returns 'failed...' messages when trying to get verification code via normal, via voice and if both methods failed.
failed! Server said missing
fail reason: old_version

I hope you can fix this or direct me to the download source of the correct/most recent version.

Thank you for all the effort in advance. 

Regards,
ninaness

**Comment by xavieritzmann** [comment]
Hello Tarek,

Exact same issue here.  Country is +1.  Telephone provider is AT&T.  v.0.9.20.  Phone number/SIM card has been working for years on WhatsApp for iPhone.

Listen, you do amazing work.  I don't think people thank you enough.  Take care,

Xavier.  Miami, FL.

**Comment by kanishkablack** [comment]
Same over here, too , no sms nor voice are reached us.

**Comment by vieri15** [comment]
Hello Tarek,

I have a problem when trying to register wazapp v0.9.20 on my N9. When I choose my contry (Côte d'Ivoire), the contry code display (+712) is not the good one. The coorect contry code for Côte d'Ivoire is +225.
So how can I solve this problem?

Thanks.

**Comment by ninaness** [comment]
I was able to find a copy of v0.9.19 at a blog
http://nokiagadgets.com/2013/04/10/wazapp-n9-update-fixed-the-send-media-bug/

Tried it but it took so much time for the sms verif code so I interrupted the process and chose Voice. This resulted to problems too. If you want to try and wait for the sms verif, check the link and download from the dropbox mirror.

Let me know what happens on uour side.

And if anyone else is reading this, I hope you can help confirm wheter v0.9.20 or v0.9.19 are conpatible with meego PR1.2. I haven't got the chance to update my firmware and don't have the reaources now.

**Comment by pameladda** [comment]
hello, i'm having problems with my registration... It says i tried too many times with all methods, what can i eo???

**Comment by pallokallo** [comment]
install bluestacks then whatsapp and voice code to your phone and then set it to openwhatsapp in N9, works

**Comment by pameladda** [comment]
it doesnt let me... i'm stuck... but i have to take my phone to a technic

**Comment by ninaness** [comment]
Bluestacks worked. Thanks pallokallo.

**Comment by piloti001** [comment]
Essentially, the same issue.
Nokia N9, [up to date software] version 0.9.2 of Wazapp, Background Data working [per suggestion] +41 mobile....
Error message is "old version"........
See image.
Thanks
![openwhatsapp_2](https://f.cloud.github.com/assets/5045118/824239/2e2d81b4-f03f-11e2-89fb-f3f403e46510.JPG)

**Comment by CODeRUS** [comment]
follow support thread in forum: http://talk.maemo.org/showthread.php?t=84318
this is bugracker, not chatroom :D

**Comment by sarunasb** [comment]
MeeGo 1.2, PR1.3 on US AT&T. Wazapp 0.9.2. 

Every registration attempt results in "fail reason: old_version".

**Comment by smitp** [comment]
+1

**Comment by pallokallo** [comment]
http://openrepos.net/content/wazapp download nightly, if you are having problems

**Comment by dido-ayad** [comment]
@tgalal 
Hello,
I had Wazapp on my N9 and i got its code from bluestacks app and it was working great
Then i had to fix my Cellphone & restore it and i had to reinstall Wazapp so i had to register again
But everytime i Register i got an Error saying "Old_Version" and its never fixed even i try to get the code from same program "Bluestacks" and i entered it but i keep getting same error "old version"
i been looking allover ur sites & forums but i cant get it fixed...
Please help me out..
Thanks

**Comment by CODeRUS** [comment]
bad luck. the answer is behind your question.

**Comment by piloti001** [comment]
This is, to say the least, a little cryptic. The 0.9.20 build has the error message "old version " that you describe, however, CODeRUS, despite the crypticness has made a working build, which is the 0.9.20 nightly 24. This does work very well. It seems however it is not possible, for whatever reason to make this the default version.Hunt out the nightly build and it will work.Cheerio.Sent from my BlackBerry® PlayBook™www.blackberry.comFrom: "CODeRUS" notifications@github.comTo: "tgalal/wazapp" wazapp@noreply.github.comCC: "piloti001" email@piloti.org.ukSent: 3 August 2013 10:37Subject: Re: [wazapp] failed registration v0.9.20 (#274)bad luck. the answer is behind your question.

**Comment by sarunasb** [comment]
N9/MeeGo 1.2 PR 1.3 on AT&T here. I tried 0.9.20-nightly-24 both as a .deb download and by adding coderus repository and installing via APT. Registration seems to start, but then waits for SMS or reg. voice call forever. Not sure whether registration is not really sent or WhatsApp ignores reg. request for whatever reason.

Anyone succeeded registration with N9 and 0.9.20-nightly-24?

Is there any other way to register?

Thanks.

**Comment by CODeRUS** [comment]
yup. you should use http://whitesoft.dyndns.org:2222/whatsapp_sms for requesting code. wazapp need some new changes.

**Comment by azmir786** [comment]
I've already downloaded wazapp nightly-24 but they dont send me the verification code. I Already use the link to give a verification. But when I put the code wazapp take an error old_version .. Help me :(

**Comment by sarunasb** [comment]
Thank you, requesting registration code via http://whitesoft.dyndns.org:2222/whatsapp_sms worked and entering it manually from Wazapp 0.9.20-nightly-24 worked.

**Comment by vieri15** [comment]
sorry but how does it work? Where did I get MCC and MNC? when I type my phone number I get a message "code request failed" "Invalid phone number". Please I need Help!

Christian ADIAFI

Date: Mon, 5 Aug 2013 07:10:52 -0700

**Comment by CODeRUS** [comment]
well, i don't know... google?
and Invalid phone number means Invalid phone number. You should use international number format ;)

**Comment by vieri15** [comment]
ok but what is MCC and MNC? what does it mean? and the phone number is the international format.. I am in Côte d'Ivoire so it is +225xxxxxxxx!

Christian ADIAFI

Date: Mon, 5 Aug 2013 07:25:33 -0700

**Comment by knobtviker** [comment]
Really??
http://lmgtfy.com/?q=MCC+MNC

Stop spamming here. Issue resolved. Use other ways of communication to learn.

**Comment by CODeRUS** [comment]
http://mcclist.com/mobile-network-codes-country-codes.asp
for example

**Comment by vieri15** [comment]
ok thanks! I'm going to try again.

Christian ADIAFI

Date: Mon, 5 Aug 2013 07:42:31 -0700

**Comment by roor1983** [comment]
Hi, I deactivate roaming connections on my N9, so when I'm in roaming wazapp try to connect, and I've the connection available always popup on the screen, until I close wazupp.
version 0.9.20 nigthly

**Comment by LayanAms** [comment]
Hi Tarek. 
Actually i have the same problem with my N9, when i register it keeps saying server said : old_version 
i hope you could find a solution or to fix this problem.

Thank you.
![2013-08-24_13-01-23](https://f.cloud.github.com/assets/5313680/1027120/2bbf11fa-0e6b-11e3-8a10-636ee78a86fb.png)

**Comment by Arthur1010** [comment]
Hi Tarek

I was using my wazapp 0.9.20 perfectly until i changed my line, it is now giving me the version_too_old error, help pliz. tried to follow the previous comments but I dont know where I can get the nightly-24 thing. help please

thank you

![c2a55790-b980-11e2-893d-305c765efe12](https://f.cloud.github.com/assets/5328212/1040634/b916436e-0fbc-11e3-8b4f-9cba1a049942.png)

**Comment by eddie12** [comment]
hi CODeRUS. I have downloaded the nightly 24 and installed it as per your conversation on the wazapp issues. But i still get the old version message. what am i doing wrong? please help me. I am not a fundi with these type of stuff.

Or can someone else help me.

**Comment by CODeRUS** [comment]
you can use https://github.com/shirioko/WART for requesting code
or online:
http://whitesoft.dyndns.org:2222/whatsapp_sms

**Comment by eddie12** [comment]
Thank you but it is still giving me a error of please enter a valid code!!

**Comment by eddie12** [comment]
Good Morning CODeRUS

I have tried everything that  can but it still does not want to work.

**Comment by laclasse** [comment]
CODeRUS,  apologies for commenting here, but this is still an issue for me or please let me
Here what i have tried:
- I am on  N9 PR1.3 latest all apps updated, not in developer mode, but external app sources allowed.
- i first downloaded wazapp for N9 from the openwhatsapp.org from the N9 itself over wifi yesterday, installed dependencies, app itself and launches, np.
  - Registrations: enter my phone number -> spinning wheel -> back to previous page -> fail_reason -> old version, all subsequent methods fail successively in the exact same way.
    All the links I goggled for the nightly 24 0.9.20 seems to point me to the same file and all fail with the same reason, same for the note at the bottom of the main web page.

Lastly, your web tool gives me: Code request failed. Reason: bad parameters passed to code request
And yes I do enter my phone in international number format, as in after your "+" sign in input box, I have 44 (i am in the UK) then omitting the first zero and the rest of my number. I even tried leaving the first 0 of my mobile number and received the same error. I see it worked for others and wonder simply what i mis-read or doing wrong?

Desperately, I used wine to run WART with even lesser results (Linux user here). I am in desperate need of this app in the next 15 days, many many many thanks in advance for any help support and pointing what what i am doing wrong. Cheers.

**Comment by laclasse** [comment]
yay nightly 35 solves all previously mentioned issues :-) !!! Many thanks.
Link here: http://harmattan.openrepos.net/coderus/pool/main/w/wazapp/

Thanks!!!

**Comment by Carlos7UA** [comment]
Hi everybody, I had the same registration issue, when typing my phone number and requesting the activation code I got the error: "Fail reason: old_version". I tried a lot of things, spent all day long looking for a solution in forums, posts, etc. and nothing solved the issue. Finally I found a solution that worked which I describe below.
1. Go to:  https://www.facebook.com/l.php?u=https%3A%2F%2Fopenrepos.net%2Fsites%2Fdefault%2Ffiles%2Fpackages%2F26%2Fwazapp_0.9.20.0nightly35_armel.deb&h=9AQGU1fSz
           *Here you will be able to download a modified Wazapp version 0.9.20 called 
             "wazapp_0.9.20.0nightly35_armel.deb"
2. Uninstall any previous version of Wazapp you have in your N9 and install this new version.
3. Go to:  http://whitesoft.dyndns.org:2222/whatsapp_sms      type in your phone number with country code.
           *Here you will be able to register your phone number manually so you get the SMS with the 
            verification code to register your account (I had to try twice, so maybe you will need to be patient and try 
            more than once, if you don't get the SMS in some minutes, wait for like a couple of hours and try again
            until you get it).
4. Then, run the installed Nightly35 version Wazapp and try to get the registration code by SMS, when it fails, select "Enter code manually" and type in the 6 digit code you got in the SMS and...
VOILA!!! You should have your number registered and your Wazapp ready to work like any previous Wazapp version.

This solution worked for me, I hope this helps you all too and saves you a lot of time trying to find the solution and fixing the problem. 

Peace

**Comment by ninaness** [comment]
Now also working on my phone. Thank you everyone for resolving our problem.

**Comment by kingGee** [comment]
im also having problems with registration. had the latest version of wazapp intsaled, worked a few days then login failed and it promted me to retegister. Tried every thing i saw on this platform and it failed. when I request for a registration code using one of the links i found here it says request failed: reason blocked. Tried registering using blueStacks then i get a message that my phone number is no longer allowed to use the service (whatsap). What should i now. Changing my number is not an option and I really need the application.please help.

**Comment by cj3b** [comment]
hi

a have also a problem by registration of whatsapp. i have installed the latest version 0.9.22, and ihave recived the code by using the following link : https://coderus.openrepos.net/whitesoft/whatsapp_sms
so i got a 6 digit code, bud when i type the code by whatsapp, always the message arrive "failed: server said old version" i type the code like this xxx-xxx and like this xxxxxx and the first 3 digits or the las 3 digits, everytime the same message....

what should i do ?

thanks

**Comment by LayanAms** [comment]
Hey, I would actually love to help you but I gave up on Nokia, I got a new iphone its MUCH better, easier and with a good quality, I prefer you bring one too trust me, Nokia died since ages, everyone is on the latest versions of phones. Sorry again I couldn't help. Thank you.

Layan.
