### ISSUE TITLE
Registration Failed: 'old_version'

### ISSUE THREAD

**Issue by palacex** [tgalal/wazapp#283]
Hi.
I'm try to register account and got an error.
Error message: Failed! Server said 'old_version'

Phone: Nokia N9 
OS: Meego Harmattan 1.2, version PR1.3

**Comment by piloti001** [comment]
Bascially, if you doanload the "normal" doanload from the OpenwhatsApp site, it will fail.
You're getting the same issues I did.
You need to find the "nightly build" link for nightly 24 [check my previous posts for the link] and this will work. Or at least it did for me and my wazzap is now working just fine.
 
Hope this helps.
 
P.

**Comment by palacex** [comment]
Thanks a lot, i found it. 
It's works.
