### ISSUE TITLE
Failed: old_version Nokia N9

### ISSUE THREAD

**Issue by KarimTarabishy** [tgalal/wazapp#284]
I have tried the normal version and the nightly version 24 & 34 they both give the same error. Also tried to make the activation from yowsup it said it is outdated!!

**Comment by CODeRUS** [comment]
whatsapp changed code requesting and no more tokens for now. you can request core using WART only.
https://github.com/shirioko/WART

**Comment by KarimTarabishy** [comment]
And then what, how by using this software can I the whatsapp on my mobile work?

**Comment by Thaodan** [comment]
you use wart to request the code nor to chat

**Comment by KarimTarabishy** [comment]
Ye I know this part and I did request the code, now what can I do with this code?!

**Comment by mackride** [comment]
Hi, im kind of new in this things, is there a solution for the message OLD_VERSION from wazapp? o what ive to do to fix it?

**Comment by ghost** [comment]
I'm having the "OLD_VERSION" error, and I used wart to request my code. All went well, and I got a long code (28 characters), but I don't understand what I'm supposed to do with this code?
