### ISSUE TITLE
Feature restoration - smileys/emojis and message forwarding

### ISSUE THREAD

**Issue by adibha** [tgalal/wazapp#297]
I have a small request. I just updated to wazapp 0.9.22 and I cannot forward messages any more. The option was there with 0.9.20 nightly 34.
Is there any specific reason for that option being removed?

The smileys now appear as a separate popup. I think this makes it a little slow. Moreover, if I want to insert multiple of them, it involves the popup multiple number of times.
In old version, smileys used to appear where normal keyboard appears.
Any specific reason for behavior change?

I appreciate your time and efforts in continuing the development for "now officially dead" platform. I wish I was able to contribute. But, I don't even know "P" of Python...

**Comment by CODeRUS** [comment]
You used nightly version. Its features was never allpied to mainline wazapp.

Just close this issue and use applications as is.

**Comment by adibha** [comment]
@CODeRUS :Alright..
