### ISSUE TITLE
Keyboard closes after each message sent

### ISSUE THREAD

**Issue by tgalal** [tgalal/wazapp#3]
After each sending of a message, you have to reclick on textarea to-open the VKB, which is inconvenient in case one wants to send successive messages.

**Comment by knobtviker** [comment]
This is not really an issue but more of a matter of habit.
If user sends single messages successively VKB should stay open but then user doesn't have the ability of multiple lines separated by Return key.

**Comment by jsfdez** [comment]
A solution could be to add a second button for "send and continue writting".

**Comment by dcastrog** [comment]
I know its late to give my opinion, but the enter key could have been used to send message and keep the VKB open, and the send button as "send message and close VKB"
