### ISSUE TITLE
Registration failed with success-attached::787

### ISSUE THREAD

**Issue by muggenhor** [tgalal/wazapp#30]
Do you still have the code for 1.8? Because while I did not manage to register with 2.5 (I got a very nice message saying 'success-attached::787' every time, except when I got fail-too-recent::X), I could register with 1.8 (I had tried 1.6 also, that failed as well).

So somewhere from 1.6 -> 1.8 something about registration changed such that it started working for me, while at the same time somewhere from 1.8 -> 2.5 it got broken again.

Unfortunately this respository doesn't contain any code from that time/version-period so I can't debug it myself. Additionally registration succeeded with 1.8 so I doubt I'll be able to reproduce it again.

**Comment by tgalal** [comment]
There you go, http://www.wazapp.im/downloads/wazapp_0.1.8_armel.deb
Try it and let me know if it works for you.

**Comment by muggenhor** [comment]
> Additionally registration succeeded with 1.8 so I doubt I'll be able to reproduce it again.

Registration resides in the C++ source right? So in order to debug that would be needed, not the binary.
