### ISSUE TITLE
How can i re-new my wazapp ?

### ISSUE THREAD

**Issue by Sherif78** [tgalal/wazapp#308]
Dear Mr. Tarek,

Re to above mention subject please i need your help to re-new my subscription in wazapp because my subscription has expired last week and i don't know how can i re-new it.

my mobile: Nokia N9
wazapp ver : 0.9.22

Thank you very much
Sherif Fathy

**Comment by CODeRUS** [comment]
you need to pay whatsapp $1/year

**Comment by CODeRUS** [comment]
http://www.whatsapp.com/payments/cksum_pay.php?phone=pn&cksum=md5
where pn = your international phone number with no leading +
md5 is hex encoded md5 of (pn + "abc")

**Comment by Sherif78** [comment]
But is one method of payment for "whatsapp" and "wazapp" ?.. There is no difference between them?

**Comment by CODeRUS** [comment]
please read: https://github.com/tgalal/wazapp/blob/master/README.md
wazapp is client application for whatsapp service.

**Comment by Sherif78** [comment]
Thank you Mr. CODeRUS for your reply, but the link you provide me above to pay didn't work, would you please check it and send it again ?

**Comment by CODeRUS** [comment]
you should replace pn and md5 with your data

**Comment by Sherif78** [comment]
forgive Mr. CODeRUS for multitude my questions but i really can't understand what is "md5" ?
so would you please explain it for me ?

**Comment by Sherif78** [comment]
Dear All, what is "MD5" ? what does it mean ?

anybody can help me ?

**Comment by CODeRUS** [comment]
http://lmgtfy.com/?q=md5+string

**Comment by Sherif78** [comment]
I have failed, Damn this complex application 
Why all this complexity? Why all this hardship and all the fuss in order to renew the subscription?

**Comment by CODeRUS** [comment]
just buy officially supported phone. android, ios, winphone and etc.

**Comment by Thaodan** [comment]
``` bash
prinf ${pn}abc | m5dsum 
```

should generate the md5sum on any unix system

**Comment by CODeRUS** [comment]
ah sure, forgot N9 have terminal, thanks @Thaodan :)

**Comment by CODeRUS** [comment]
@Sherif78 open meego terminal and type:

```
printf 123456789abc | md5sum
```

where 123456789 - your phone number. and use phonenumber and result value in link parameters

**Comment by Sherif78** [comment]
@CODeRUS  Thank you very much Mr. coderus for your help
i followed your last instructions and renewed my wazapp successfully

thank you very much again my friend :)
