### ISSUE TITLE
Status overflow in contacts

### ISSUE THREAD

**Issue by tgalal** [tgalal/wazapp#33]
Need to truncate contacts statuses: See http://2.bp.blogspot.com/-FPhqNo76B4o/T8HjLMSGT9I/AAAAAAAAApQ/pogOgHSfSAs/s400/2012-05-27_11-00-21.png

**Comment by knobtviker** [comment]
Apparently, this happens with emoji only. Normal strings get elided as they should.
My question is: do you want to cut of truncate the status or increase the height of the item and show the whole status?

**Comment by CepiPerez** [comment]
I think the best we can do is cut the label containing the status
This way it looks better than having different sizes in contacts list

**Comment by knobtviker** [comment]
Label width is not calculated properly so cutting the label didn't work for me. String itself has to be truncated if too many emojis are counted in it. Both portrait and landscape. Emoji is 32 or 20px in width. Times accounted ones. It gets complicated and still didn't fix it.

**Comment by CepiPerez** [comment]
I'll fix it tomrrow.

**Comment by CepiPerez** [comment]
Fixed!
