### ISSUE TITLE
Not syncing contacts

### ISSUE THREAD

**Issue by naii** [tgalal/wazapp#34]
Wazapp 0.2.6. doesn't sync my contacts.

It says: "No contacts yet. Try to resync"

**Comment by tgalal** [comment]
Follow the steps here http://talk.maemo.org/showthread.php?t=84318 under "Recurring Problems" then report back. Thanks.

**Comment by naii** [comment]
Thx tgalal. It runs perfectly fine on the terminal and starts with no errors. Still, no contacts after sync.

**Comment by tgalal** [comment]
Please just post the output or email it to me if to contains private data such as phone numbers. It would be help. Thanks.

**Comment by naii** [comment]
Oh sorry. I sent you an email.
