### ISSUE TITLE
[Contacts List] Case Sensitive Error 

### ISSUE THREAD

**Issue by funkycode** [tgalal/wazapp#35]
I just paid attention that C and c are not in the same sub category in contacts. So it shows all the contacts with Capital letters in alphabetic order, and than all small letters in alphabetic order again =\

**Comment by CepiPerez** [comment]
fixed
wait for update

**Comment by funkycode** [comment]
thanks. I do wait for update as i know it comes with a lot of tasty things. closing issue than =)
