### ISSUE TITLE
Connection broken when running in background

### ISSUE THREAD

**Issue by yautak** [tgalal/wazapp#38]
When the program is closed by swiping from the top of the screen (running in background without quitting), the connections is broken when the data network is shift from one to another (e.g. 3G to wifi and vice versa).

**Comment by knobtviker** [comment]
I must say, I'm having the same issue eveyday because I'm on my home WiFi then get cut of in elevator on 3G and then outside it never connects back on 3G...
So, I confirm this issue...

**Comment by jalyst** [comment]
So this is finally fixed? W00t!
