### ISSUE TITLE
No message confirmation in group messaging.

### ISSUE THREAD

**Issue by dcastrog** [tgalal/wazapp#45]
I know group messaging is not fully supported yet, but since you guys are developing it now, I will post this just to make sure it is not overlooked.

When sending messages, there is no confirmation that the message was received, only confirmed that the message arrived whatsapps server.

**Comment by pablosambuco** [comment]
I think that is the default behavior, even in the official client
This shouldn't be a bug

**Comment by tgalal** [comment]
@pablosambuco you are right. see #76
