### ISSUE TITLE
Wazapp random crashes

### ISSUE THREAD

**Issue by godofwar424** [tgalal/wazapp#57]
At first I thought this was due to switching between WiFi and 3G and also loosing signal when going underground ect.

But this happens even when I am connected fine to the internet and haven't had to switch connections at all.

For example: Been connected to my WiFi at home all night with a strong connection, no dropouts, yet Wazapp will still crash, here is the log at the moment of crash.

socket read crashed, reason [Errno 9] Bad file descriptor
socket read crashed, reason [Errno 9] Bad file descriptor
Socket closed, got 0 bytes
Socket closed, got 0 bytessocket read crashed, reason [Errno 9] Bad file descriptor socket read crashed, reason [Errno 9] Bad file descriptor
Socket closed, got 0 bytes
socket read crashed, reason [Errno 9] Bad file descriptor
Socket closed, got 0 bytes

socket read crashed, reason [Errno 9] Bad file descriptor ONLINE
Socket closed, got 0 bytes

Segmentation fault

**Comment by damaltor** [comment]
I am experiencing exactly the same issue, usually after 4-5 hours. Waking up in the morning always means restarting wazapp because it crashed a few hours ago in the night.
This did not happen AFAIR before 2.6.0

**Comment by gtfunes** [comment]
I've been having the exact same problem since v0.2.6.

**Comment by bakedbeanz** [comment]
The same problem. 4-5 hours. Sometimes while using it.
