### ISSUE TITLE
Status Display in another devices

### ISSUE THREAD

**Issue by ghost** [tgalal/wazapp#58]
It appears that Wazapp users are constantly shown as online while the app is open or running in the background, and as offline if they Quit wazapp from within the app itself.

Original Whatsapp users are shown as online only if they have the app open at the time, and as "last seen on..." if they have it running in the background, so it'd be nice if wazapp could behave in the same way.

I don't know much about coding, but i think this behaviour may be related to the ping the app needs to keep the connection alive, though i'm not sure if it pings whatsapp servers (which would explain why the servers see the app users as active in the chat all the time) so a good start could be to disable this ping and see if it affects the status display from other devices, and if it does, try to find a way to keep the connection alive without being shown as online.

**Comment by CepiPerez** [comment]
I understand what you mean. But in my opinion, this is a whatsapp error.
What's your status in other IM apps, like msn, when the main window is hidden?
If you are connected, no matter if in background mode (or minimized in desktop apps), you still online for all your friends.
Anyways, it's not my decision to change or keep it as it is now.
Let's wait for Tarek to see what he thinks.

**Comment by tgalal** [comment]
"Original Whatsapp users are shown as online only if they have the app open at the time, and as "last seen on..." if they have it running in the background, so it'd be nice if wazapp could behave in the same way."

This is how Wazapp actually works as well. As soon as the window loses focus you will become "not online" for other users after I think 15 seconds. If it's currently behaving differently then it's a bug.

**Comment by ghost** [comment]
Personally, I agree with CepiPerez, since it's logical to appear as online whenever we're able to get messages and reply to them. However, whatsapp seems to think different, and it seems tgalal too :P

Anyways, i'm not doubting the work done so far, but there's people at the dev thread who confirmed this behaviour. Sadly i can't try to reproduce it myself at the time since I don't own a N9, but a friend does (i follow the development because of that), so I'll try to ask her to lend it to me for a few tests later and see if it's working properly or not. 

Thanks both of you for the quick replies.
