### ISSUE TITLE
Emotion Problem

### ISSUE THREAD

**Issue by TMavica** [tgalal/wazapp#70]
Dont know anyone mentioned it or not. When I type a message, last with a emotion, when pick up a emotion, the emotion will go in front of the message, I need to rearrange to make it in the end of the WORD

**Comment by CepiPerez** [comment]
The emoticon is inserted at cursor position
I test it a lot and it's working fine here
Can anybody confirm this issue?

**Comment by TMavica** [comment]
Cepi, example:

i typing "hello", then click the emoticon and pick up, the emoticon will appear in front of the "hello", >> emo hello
more example: I type "hello hello hello", then pick up a emoticon, then will become "hello hello emo hello"

sorry for my bad english, hope you understand

**Comment by CepiPerez** [comment]
Don't worry. My english sucks too.
Are you using predictive text? 
If the word stills underlined when you insert the emoticon, that's the reason
It's not a bug. That's how it works

**Comment by TMavica** [comment]
O shxt, I understand what you mean.
Close issue.
