### ISSUE TITLE
Cant syn the user who live in other country

### ISSUE THREAD

**Issue by TMavica** [tgalal/wazapp#73]
I live in Hong Kong, all my friends phone number is saved in contact without a country code, I can syn them in wazapp very well, all they can show. but one of the friends cant be show, he live in Australia. The contact I saved is with country code, but I cant get him in wazapp contact, need tell me msg me, then his contact will be showed.

**Comment by CepiPerez** [comment]
Fixed in latest dev. Please close

**Comment by tgalal** [comment]
Confirmed
