### ISSUE TITLE
"Enter as Send button" feature

### ISSUE THREAD

**Issue by soryuuha** [tgalal/wazapp#79]
Hi tarek,

I liked ttis small features on official whatsapp client :D

mind to put it in on upcoming release? :D

**Comment by aleejaved** [comment]
i'll vote against this. enter button should take us to another line.

**Comment by pablosambuco** [comment]
This is already included in last development version (at least in cepi branch)

**Comment by aleejaved** [comment]
if its implemented, i'd like to suggest, please make an option for it in settings menu.

**Comment by pablosambuco** [comment]
+1 to @aleejaved comment

**Comment by soryuuha** [comment]
@aleejaved i\t is an option in settings menu for official whatsapp, not forced.
@pablosambuco thanks for the info! i close this issue then =)

**Comment by aleejaved** [comment]
i know its not an option, but everyone has their own likes and dislikes.
not everyone will like enter as send button, and vice versa

**Comment by tgalal** [comment]
Should be optional

**Comment by soryuuha** [comment]
this already in Cepi build, and it is optional. CloseD!
