### ISSUE TITLE
Emoji are sent twice

### ISSUE THREAD

**Issue by pablosambuco** [tgalal/wazapp#80]
If there's no other text in messaje, emoji are sent twice. (latest cepi branch)
Screenshot: http://bit.ly/MVz7qo

**Comment by CepiPerez** [comment]
It happens to me once, but after restarting wazapp never happens again
So I can't reproduce it again to find where's the bug. Can you?

**Comment by pablosambuco** [comment]
I can't reproduce it... I did a clean install last weekend and this issue is not happening any more... 
I'll let you know if it comes back :)
Meanwhile, I close this issue
