### ISSUE TITLE
Special HTML characters aren't sent properly

### ISSUE THREAD

**Issue by pablosambuco** [tgalal/wazapp#81]
Characters as " (quotation mark)  are not sent properly (latest cepi branch)

Screenshots:
http://bit.ly/MVzUYi
http://bit.ly/MVO3F0

**Comment by CepiPerez** [comment]
I've fixed " and & characters right now
AFAIK those are the only ones that doesn't work properly
Did you find another one?

**Comment by pablosambuco** [comment]
I've just made a few tests:
"<" and ">" are shown ok in my n9, but they are sent as "& lt;" and "& gt;"

I believe those are the last ones to fix

**Comment by pablosambuco** [comment]
Fixed on latest branches. Closed
