### ISSUE TITLE
Long messages preview overlaps labels

### ISSUE THREAD

**Issue by pablosambuco** [tgalal/wazapp#82]
In chats window, long messages previews overlaps other labels (at least when the message includes emoji) (latest cepi branch)

Screenshot: http://bit.ly/MVO4c3

**Comment by CepiPerez** [comment]
I've already fixed it

**Comment by pablosambuco** [comment]
@CepiPerez, it's working on long lines without emoji, but the preview overlaps other labels at least for me if the message includes emoji, that screenshot is 3 days old, while the last change in the development branch is 18.
A similar issue was on version 0.2.6 with the status messages on the contacts tab

//En español, que seguramente nos entenderemos mejor: funciona bien para lineas largas sin emot, pero el preview se superpone con otras etiquetas (nombre de contacto, horario del mensaje) si el mensaje incluye un emoticon. El screenshot es de hace 3 días, mientras que el último cambio en el branch es de hace 18.
Estimo que es un problema similar al que había en la v 0.2.6 con el mensaje de estado en la solapa de contactos

**Comment by CepiPerez** [comment]
That's because I didn't merge some fixes in cepi branch
Tgalal is working in QML files, so I'm waiting for his changes to add some fixes

**Comment by pablosambuco** [comment]
Perfect then.
Issue closed! :)

PS: I **need** v0.2.7... I wish I had more experience on py+qt
