### ISSUE TITLE
Frequent upgrade notifications from WhatsApp Server

### ISSUE THREAD

**Issue by ginggs** [tgalal/wazapp#86]
Since 2012/07/03 I have been getting the following message from 'Server' almost daily:

"New version of WhatsApp Messenger is now available. Please visit http://www.whatsapp.com/nokia/ and upgrade to the latest version.  Your upgrade will be free of charge."

**Comment by aleejaved** [comment]
change the string to the latest symbian version which is 2.6.99
http://talk.maemo.org/showpost.php?p=1238032

**Comment by pablosambuco** [comment]
Perhaps we can avoid having a constant for this
I think parsing whatsapp.com (or any page or repository) for the latest version might do the trick...

This wrote a small code that gets the latest Symbian release from [whatsapp's download page for nokia](http://www.whatsapp.com/nokia). 

See below:

[waversionparser.py](https://gist.github.com/3719661)

**Comment by ginggs** [comment]
Good idea, but WhatsApp seem to be blocking any 'Symbian-xxx' and 'S40-xxx' resources now.  We have switched to 'iPhone-xxx'.
189d755577588c31dee863de9f2b56a5e33dbf60

**Comment by pablosambuco** [comment]
still, I don't know if is a good idea to have a constant string, 
with a little work any other release's version can be parsed:
- android: http://www.whatsapp.com/android/
- iphone: http://www.whatsapp.com/appstore/
