### ISSUE TITLE
Emoticons on dev build 2.6.90

### ISSUE THREAD

**Issue by abun880007** [tgalal/wazapp#88]
Hi

just to let you know since I have upgraded to dev build when I add emoticons into a message they do not get shown the the sent message bubble. Just wanted to highlight this as would not want ti happening on next stable release.

regards

abun880007

**Comment by abun880007** [comment]
just to update this problem has been resolved on CepiPerez latest build 0.2.6-5-gcc36cde, just so your aware when merging to main build

**Comment by tgalal** [comment]
Thanks, fixed in dev
