### ISSUE TITLE
Errors on registration, and no verification code received

### ISSUE THREAD

**Issue by pinaraf** [tgalal/wazapp#89]
Hi

I tried to use wazapp on my N950, but when I tried to register, I never received any SMS with the confirmation code.
Now, each time I try to register, I get the following errors :
- for SMS registration : «Failed. Server said: fail-too-many»
- same for «code through voice»
- when I try the «everything failed» button, I get «Failed. Server said: unknown reason»

Is there any way for me to get that verification code back ? I tried removing and reinstalling the application, nothing worked…
And I don't have any other phone to try the «official» application (unless there is an official one for N900 ?)

**Comment by laoyang945** [comment]
The same on my N9, PR1.3

**Comment by ericblade** [comment]
I have same problem while working on a completely different project, I was working on registration, when I realized after getting a dozen or so successful responses, but never receiving an actual code, that I wasn't setting the User-Agent.. as soon as I set the User-Agent, it started responding with the fail-too-many.

I've located a completely different registration URL system, but can't seem to get that to work, either, it always sends me a SMS telling me that my WhatsApp needs to be updated.

**Comment by skrech** [comment]
I have absolutely the same problem as pinaraf but on N9 PR1.3.

**Comment by ericblade** [comment]
I have spent quite some effort decoding the current S40 nokia version to dig up what URL and information it's providing.. code retrieval according to that code is still at r.whatsapp.net/v1/code.php?dot=1&cc=1&in=707..........&lg=en&lc=US&mcc=000&mnc=000&method=sms&imsi=00000000000000, and UA should be something like: WhatsApp/2.3.39 S40Version/04.60 Device/nokiac3-00 

still getting error.  So, it is my guess at this point, that either there's a completely different registration system sneaking around in here, or the S40 app simply cannot register anymore.
