### ISSUE TITLE
Login process fails

### ISSUE THREAD

**Issue by vkotovv** [tgalal/wazapp#90]
After recent update, login process started to fail. I guess this is true for wazapp too. The key is several bytes change in streamStart method. Please take a look at https://github.com/venomous0x/WhatsAPI/issues/29. 
The possible solution could be (see https://github.com/tgalal/wazapp/blob/master/src/client/protocoltreenode.py#L328): 

``` python
def streamStart(self,domain,resource):
   self.realOut.write(87);
   self.realOut.write(65);
   self.realOut.write(0);
   self.realOut.write(4);
```

I've pushed the fix to WhatsAPI, but dont know what branch to use for wazapp, so please fix it by yourself.

**Comment by knobtviker** [comment]
Vadim, thank you for the fix, that helped a lot.

**Comment by CepiPerez** [comment]
Can someone close this? Thanks!
