### ISSUE TITLE
"Select picture" dialog does not show pictures with upper case file endings

### ISSUE THREAD

**Issue by flesser** [tgalal/wazapp#92]
Using Cepi build 29.08.2012, the "Select picture" dialog does not show pictures with upper case file endings like "picture.JPG".

Modifying the filters in UI/Conversations/SendPicture.qml to also accept upper case file endings fixes this.

**Comment by CepiPerez** [comment]
Latest build uses python to search image files, not the shitty QtMobility.Gallery. So it's fixed. Please close.
